//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Banking.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Transaction
    {
        public int Id { get; set; }
        public int AccountFromId { get; set; }
        public Nullable<int> AccountToId { get; set; }
        public decimal Amount { get; set; }
        public System.DateTime Datetime { get; set; }
        public string Description { get; set; }
    
        public virtual Account AccountFrom { get; set; }
        public virtual Account AccountTo { get; set; }
    }
}
